Preparation for 1.0 release.
ymcatwincities/openy_gated_content pull request #42
Opened 2020-10-02 14:06 UTC by anpolimus

2020-10-06 13:13 UTC, podarok requested changes
Should be changed everywhere, please

2020-10-06 13:13 UTC, podarok commented on modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml
> +      plugin: migration
```suggestion
      plugin: migration_lookup
```
see https://www.drupal.org/node/2861226

2020-10-06 13:24 UTC, podarok requested changes

2020-10-06 13:24 UTC, podarok commented on modules/openy_gc_storage/openy_gc_storage.install
> +    'field.storage.eventseries.field_ls_category',
not enough for storage configs. You need to use a different code here to have fully supported storage updates
See https://github.com/ymcatwincities/openy/pull/2215/files#diff-b205ecc1e2f71f78ba8f3db948e7cd27R108

2020-10-06 14:25 UTC, podarok requested changes

2020-10-06 14:25 UTC, podarok commented on modules/openy_gc_shared_content/src/Controller/PreviewController.php
> +    $data = $instance->jsonApiCall($shared_content_source_server, $query_args, $uuid);
looks like this was a bug

2020-10-06 14:26 UTC, podarok commented on js/gated-content/src/components/LogoutLink.vue
> +    <a href="/user/logout">Sign out</a>
not a blocker, but still, would be nice to QA

2020-10-07 13:09 UTC, anpolimus commented on modules/openy_gc_auth/src/GCUserAuthorizer.php
> +      $user->addRole('virtual_y');
done

2020-10-07 13:10 UTC, merged

2020-10-15 12:32 UTC, hamrant commented on js/gated-content/src/components/LogoutLink.vue
> +    <a href="/user/logout">Sign out</a>
Fixed - https://github.com/fivejars/openy_gated_content/pull/135